### ISSUE TITLE
Style fixes 

### ISSUE THREAD

**Issue by theobiabo** [uploadfly/dashboard#1]
### I will love to: 
* Update the folder structure 
<details><summary>Fix Stylings</summary>
* I will like to fix some styling 
* Update style folders

</details> 

![Screenshot from 2023-07-04 13-03-53](https://github.com/uploadfly/dashboard/assets/54102389/c0ce2bf5-0014-4f0a-8695-cc64e2aa3e6a)
![Screenshot from 2023-07-04 13-04-13](https://github.com/uploadfly/dashboard/assets/54102389/a9c751f6-2e79-45df-b32a-cf883b8d19e4)

**Comment by theobiabo** [comment]
check

**Comment by xt42io** [comment]
Thanks, if you'd like to do the things you listed above, please fork the repo, make the changes and open a PR

**Comment by theobiabo** [comment]
sure i will
